### ISSUE TITLE
Long-running 2D graph leads to access violation

### ISSUE THREAD

**Issue by jvalik** [jheinen/gr#11]
Hello,

I have the Python Qt-based GUI which is using the GR to draw eight curves. I am using the Plot once, the PlotAxes once and the PlotCurves 8-times.

I do the refresh every 40 ms. Before every refresh the curve values are shifted by one and the new value is added to the end. The X value grows by 0.04 for every refresh and thy Y values are within -1 to 1 range. All the curves are shifted in the same way, so the X axis is always in the range of approx 10 seconds, so there are 250 values within a short numeric range.

Everything goes fine for maybe 12 to 15 hours, but after that I receive this error:

origin outside current window
origin outside current window
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\qtgr\__init__.py", line 294, in paintEvent

    super(InteractiveGRWidget, self).paintEvent(event)
  File "C:\Anaconda\lib\site-packages\qtgr\__init__.py", line 104, in paintEvent

    gr.updatews()
  File "C:\Anaconda\lib\site-packages\gr\__init__.py", line 249, in updatews
    __gr.gr_updatews()
WindowsError: exception: access violation reading 0x00000000

Unfortunately, I'm unable to compile the binaries on my Win7, so cannot debug the exact place where the binary fails.

I have no idea what I am doing wrong, but in general I hope the curve values are ok.

Thank you

John

**Comment by jheinen** [comment]
Dear John,

can your script easily be changed such that the curves do not depend on any specific data source? E.g,, if you could use random values for the input data we could debug the script on one of our systems or simulate the GR calls in a small C program.

Regards,
Josef

**Comment by jvalik** [comment]
Hello Josef,

I prepared a simple demo by removing all unnecessary parts replacing them
with the random values. Also I speed it up to make the error happen sooner.
This demo was running through the night and in the morning the error was
already raised. So I suppose it has something to do with the number of the
cycles, because on our real system it happened later, but it had slower
timer set.

I didn't find the way how to attach the files here, so I temporarily
uploaded them to http://inobox.cz/pm/gr_fail.zip.

Thank you!

John

2015-05-30 15:42 GMT+02:00 Josef Heinen <notifications@github.com>:

**Comment by jheinen** [comment]
I found a memory leak in a low-level text routine which fixed the problem on OS X and Linux. I'll soon check the Windows version - so the problem hopefully will be fixed in v0.13.1.

Regards,
Josef

**Comment by jvalik** [comment]
Hello Josef,

I've found the new 0.13.1 version with the comment about the memory leak in Win solved. So I updated the GR and tried, but received the error again:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\qtgr\__init__.py", line 262, in paintEvent

    super(InteractiveGRWidget, self).paintEvent(event)
  File "C:\Anaconda\lib\site-packages\qtgr\__init__.py", line 69, in paintEvent
    gr.updatews()
  File "C:\Anaconda\lib\site-packages\gr\__init__.py", line 249, in updatews
    __gr.gr_updatews()
WindowsError: exception: access violation reading 0x00000000

Is it the error you've fixed or is it still in the queue?

Thank you!

John

**Comment by jvalik** [comment]
Hi Josef,

I've done some investigation and found the following:
- there is no dependency on the curves count, event not on the Plot; I've simplified my test code to just refresh the InteractiveGRWidget, which doesn't have any plot added
- each call to the InteractiveGRWidget.update() causes the additional memory allocation, which leads to allocation of all the available memory and crash
- I've tried the InteractiveGRWidget deletion and creation to avoid this memory leak hoping it will free all that additional memory allocation, but it didn't help. I deleted the InteractiveGRWidget (self.gr) using the layout.removeWidget(self.gr) + self.gr.deleteLater() + self.gr = None. The way of the deletion should be ok, since applied to another widget didn't cause any memory leak.

So I suppose there is still something going wrong inside the updatews() call. Hopefully information above will help.

Thank you

John

**Comment by jheinen** [comment]
Hi John,

could you pls run the following test-script and observe the memory consumption in the task manager?

    from numpy import arange, sin, pi
    from gr import clearws, setviewport, setwindow, axes, grid, polyline, updatews
    from time import sleep

    x = arange(0, 2 * pi, 0.01)
    while True:
        clearws()
        setviewport(0.1, 0.95, 0.1, 0.95)
        setwindow(x[0], x[0] + 2*pi, -1, 1)
        axes(0.5,0.1,x[0],-1,2,5,0.01)
        grid(0.5,0.1,0,0,2,5)
        polyline(x, sin(x))
        updatews()
        x += 0.1

I have the impression, that there is some memory leak in the Qt code ...

Regards,
Josef

**Comment by jvalik** [comment]
Hi Josef,

I've tried your code provided and it looks ok. I left it running about 5 minutes ended up with approx. 4600 samples on X axis and didn't notice any additional memory allocations. So this example looks stable.

If the trouble is somewhere inside the Qt, I should probably get into it also when calling update() on the QWidget, maybe? But I have noticed no memory leaks doing this.

Is there any other way how to use the GR in Qt? I was thinking about getting the render into some image buffer and the draw that buffer onto the canvas, but the trouble is that we are using transparent background for the graph. But anyway - do you think this could help? And how to get the rendered image from the GR?

Thank you

John

**Comment by jheinen** [comment]
Hi John,

... could you try the following code snippet, too?

    #!/usr/bin/env python
    # -*- coding: utf-8 -*-
 
    import sys
    import os
    from PyQt4 import QtCore, QtGui
    import sip
    from numpy import arange, sin, pi
    import gr
    
    class GrWidget(QtGui.QWidget) :
        def __init__(self, *args) :
            QtGui.QWidget.__init__(self)
            QtCore.QTimer.singleShot(0, self.draw)
            
            self.setupUi(self)
    
            os.environ["GKS_WSTYPE"] = "381"
            os.environ["GKS_DOUBLE_BUF"] = "True"
    
            self.x = arange(0, 2 * pi, 0.01)
     
        def setupUi(self, Form) :
    
            Form.setWindowTitle("GrWidget")
            Form.resize(QtCore.QSize(500, 500).expandedTo(Form.minimumSizeHint()))
    
        def quit(self) :
            gr.emergencyclosegks()
            self.close()
    
        def draw(self) :
            self.setStyleSheet("background-color:white;")
            gr.clearws()
            gr.setviewport(0.1, 0.95, 0.1, 0.95)
            gr.setwindow(self.x[0], self.x[0] + 2*pi, -1, 1)
            gr.axes(0.5,0.1,self.x[0],-1,2,5,0.01)
            gr.grid(0.5,0.1,0,0,2,5)
            gr.polyline(self.x, sin(self.x))
            self.x += 0.1
            self.update()
    
        def paintEvent(self, ev) :
            self.painter = QtGui.QPainter()
            self.painter.begin(self)
            os.environ['GKSconid'] = "%x!%x" % (sip.unwrapinstance(self), sip.unwrapinstance(self.painter))
            self.draw()
            gr.updatews()
            self.painter.end()
    
    app = QtGui.QApplication(sys.argv)
    if not sys.platform == "linux2" :
        app.setStyle('Windows')
    
    w = GrWidget()
    w.show()
    
    sys.exit(app.exec_())

Regards,
Josef

**Comment by jvalik** [comment]
Hi Josef,

this code reproduces the issue again.

Thanks

John

**Comment by jheinen** [comment]
Hi John,

there was a memory leak in the ``gks_getenv()`` function, which calls ``DLLGetEnv()`` on Windows. This function is required to retrieve environment variables in DLLs, such as the ``qtplugin``. The routine inquires a block of memory containing the environment variables of the calling process using the ``GetEnvironmentStrings`` function, which has to be free'd with ``FreeEnvironmentStrings`` - according to the updated documentation.

With the next release (this week), the problem will be fixed.

Regards,
Josef

**Comment by jvalik** [comment]
Great news, thanks a lot!

John

**Comment by cfelder** [comment]
I think this should be closed.

**Comment by jvalik** [comment]
Hello,

sorry of the delayed response. Last time I've tried the 0.15 version and
the issue remains. Currently I'm waiting for new version of wheel binary to
do the test with newer releases (0.17), because it's too complicated for me
to build it under win32. I'll let you know once it is tested.

Thank you

John

2015-11-24 19:53 GMT+01:00 cfelder <notifications@github.com>:
