### ISSUE TITLE
Create a mailing list of forum to support gr users

### ISSUE THREAD

**Issue by ufechner7** [jheinen/gr#12]
Hello,

I have an installation problem with gr, but I do not know, where I can ask questions.
Is there a mailing list for gr users?

Best regards:

Uwe Fechner, TU Delft

**Comment by ufechner7** [comment]
By problem is the following error message
```
In [1]: from gr import pygr

In [2]: pygr.plot([0,1,4],[3,2,5])
GKS: file open error (lib/python2.7/site-packages/gr/fonts/gksfont.dat)
open: No such file or directory

In [3]:
```
The file exists, but probably not at the place, where gks is looking for it:
```
(numba2)ufechner@TUD277255:~$ locate gksfont.dat/home/ufechner/miniconda/envs/numba2/lib/python2.7/site-packages/lib/python2.7/site-packages/gr/fonts/gksfont.dat
```
Any help appreciated!

**Comment by jheinen** [comment]
Could you explain, how you created your Miniconda environment?

I'd suggest:

    % miniconda/bin/conda create -n numba2 python
    % source miniconda/bin/activate numba2
    (numba2)% conda install -c https://conda.binstar.org/jheinen gr

Does this work for you ?

**Comment by jheinen** [comment]
We will think about a mailing list ....

**Comment by Juanlu001** [comment]
:+1:

Perhaps the SciPy folks can host a Mailman list on their servers, or if you don't want to use Google Groups you can give https://groups.io a try.

**Comment by jheinen** [comment]
You can use https://gitter.im/jheinen/GR.jl.
