### ISSUE TITLE
pendulum example generates "latex" messages

### ISSUE THREAD

**Issue by stonebig** [jheinen/gr#15]
Hi,

On  latest gr-0.14.1 (wheel from Chirstoph Gohlke) on windows 64 / matplotib 1.4.3 / Python 3.4.3

I get a strange error in Spyder console, while the pendulum itself works:

http://gr-framework.org/examples/pendulum.html

````
latex: failed to create a dvi file
'latex' latex is not recognized as an internal command
````

I don't have a Tex distribution  on my pc.

**Comment by jheinen** [comment]
For this demo, you need to have dvipng in your path. You cannot produce LaTeX output without having TeX installed, as LaTeX-API or callable run-time doesn't exist.

**Comment by stonebig** [comment]
ok, thanks.
