### ISSUE TITLE
can't install with pip on OS X 10.11

### ISSUE THREAD

**Issue by faroit** [jheinen/gr#25]
starting with a fresh environment: 

```
pip (8.1.2)
setuptools (25.1.3)
wheel (0.29.0)
```

```pip install  gr```

results in

```shell
Collecting gr
  Using cached gr-0.19.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/gr.egg-info
    writing pip-egg-info/gr.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/gr.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/gr.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/gr.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    cc -arch x86_64 -fPIC -c 3rdparty/zlib/adler32.c -o 3rdparty/zlib/adler32.o
    error: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.6" but "10.11" during configure
```

installing from source using pip and changing the ```macosx-deployment-target``` to 10.11 does work, so it would make sense to determine the OS X version dynamically during setup:

```python
'.'.join(platform.mac_ver()[0].split('.')[:2])
```
seems to work. Should I compile a PR?

**Comment by cfelder** [comment]
Dear faroit,

thanks for your report. Version 10.6 is the minimum required ``macosx-deployment-target``. Thus setup.py tries to compile with this target by default. I would like to keep the default at version 10.6 because this should allow us to create one wheel which works with OS X versions 10.6+.

Nevertheless we have to investigate why there is a mismatch::

    error: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.6" but "10.11" during configure

**Comment by cfelder** [comment]
I have reproduced your problem:

The ``MACOSX_DEPLOYMENT_TARGET`` of your python interpreter is ``10.11``. We use our own python environment build on an ``10.6`` machine which allows us to use ``MACOSX_DEPLOYMENT_TARGET=10.6`` which fails on your machine.

I suggest to use the version determined by::

    import sysconfig
    sysconfig.get_config_var("MACOSX_DEPLOYMENT_TARGET")

I will prepare a patch for that.

**Comment by faroit** [comment]
sounds good, if you open a PR i can check it out and test it

**Comment by cfelder** [comment]
I have prepared a patch in our Gerrit Code Review instance. If you already have a github checkout of ``GR`` you can easily checkout the patch with the following command::

    git fetch https://iffwww.iff.kfa-juelich.de/review/gr refs/changes/56/656/1 && git checkout FETCH_HEAD -b osx_setup

This will create a branch named ``osx_setup``.

The code itself can be reviewed on:
https://iffwww.iff.kfa-juelich.de/review/#/c/656/
