### ISSUE TITLE
Installation MacOS Anaconda 3.5 

### ISSUE THREAD

**Issue by KorbiW** [jheinen/gr#27]
Hello! 
I have some trouble installing gr on a MacOS with Python3.5 on Anaconda.
I get the following error message, no matter what way i try to install: 
...
  File "setup.py", line 1493, in finalize_options
    check_ext.finalize_options(self)
  File "setup.py", line 846, in finalize_options
    build_static.finalize_options(self)
  File "setup.py", line 117, in finalize_options
    if version[0] == 10 and version[1] < 7:
TypeError: 'map' object is not subscriptable

What can i do? 
Another question i have: 
I would like to visualize 3D-Data (some hundred datapoints/ dataset), which should rebuild as quick as possible. Is gr the right tool for this? Or would PyQtgraph or Vispy or something else be more suitable for this case? 
Thanks a lot! 
Korbinian

**Comment by cfelder** [comment]
Thanks for your report. I have created a bugfix for this issue.

https://iffwww.iff.kfa-juelich.de/review/760

In python 3 map returns an iterable map object instead of an subscriptable list.

**Comment by jheinen** [comment]
We plan to build new Conda packages next week. 

How is your 3D data organised? Do you want to plot surface plots from rectilinear data?

**Comment by KorbiW** [comment]
Thank you very much! the Problem changed... i try to investigate. 
It is radiation data in azimuth/elevation /fftbins   and i'd like to make a balloon representation of it. (Meshitem i think)

**Comment by KorbiW** [comment]
Hello! I tried the new anaconda packages and unfortunately still no success. 
Is gr Python 2 only?   
I get the following error:
`    lib/gks/x11.c:4556:11: warning: implicit declaration of function 'XDestroyWindow' is invalid in C99 [-Wimplicit-function-declaration]
              XDestroyWindow(p->dpy, p->win);
              ^
    lib/gks/x11.c:4563:9: warning: implicit declaration of function 'XCloseDisplay' is invalid in C99 [-Wimplicit-function-declaration]
            XCloseDisplay(p->dpy);
            ^
    89 warnings and 1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1`

Best regards! Korbinian

**Comment by jheinen** [comment]
Are you trying to build GR from source (``python setup.py build``) or do you want to install GR using conda (``conda install -c https://conda.anaconda.org/jheinen gr``) ?

There are also pre-built Anaconda packages (https://anaconda.org/jheinen/gr) or native installation packages for several Linux flavors provided by openSUSE Build Service (http://software.opensuse.org/download.html?project=science:gr-framework&package=python-gr). So there is no need to build GR from source ...

**Comment by jheinen** [comment]
GR can be used with any Python version. For Python 3, you manually have to set the ``PYTHONPATH`` to something like ``/usr/gr/lib/python`` - depends on the OS. I could create and upload an Anaconda package for Linux, if you have problems ...

**Comment by KorbiW** [comment]
If i try to install by ( conda install -c ...)  i get `$ conda install -c https://conda.anaconda.org/jheinen gr
Fetching package metadata .........
Solving package specifications: ....


UnsatisfiableError: The following specifications were found to be in conflict:
  - gr
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.`
 
if I try using python setup.py install  i get `....    
In file included from lib/gks/x11.c:40:
/usr/X11/include/X11/Intrinsic.h:1855:3: error: expected function body after function declarator
) _X_ATTRIBUTE_PRINTF(2,3);
....
        ^
lib/gks/x11.c:4563:9: warning: implicit declaration of function 'XCloseDisplay' is invalid in C99 [-Wimplicit-function-declaration]
        XCloseDisplay(p->dpy);
        ^
89 warnings and 1 error generated.
error: command '/usr/bin/clang' failed with exit status 1`

Finally: 
after cloning the github folder into the right anaconda folder it seems to work! 

Thank you for all the advice!
