### ISSUE TITLE
gr crashes on executing the example

### ISSUE THREAD

**Issue by HermenB** [jheinen/gr#3]
I installed gr using conda install -c https://conda.binstar.org/jheinen gr on mac osx 10.8.5. There seems to be an issue with the 'libfreetype.6.dylib'. 
When running the example from the gr website:
    from gr import pygr
    pygr.plot([0,1,4],[3,2,5])
gr crashes and leaves an item named: "libfreetype.6.dylib" in the finder favorites column, which refers to the following terminal message:

Last login: Fri Dec  5 15:01:10 on ttys002
/opt/X11/lib/libfreetype.6.dylib ; exit;
~ user$ /opt/X11/lib/libfreetype.6.dylib ; exit;
-bash: /opt/X11/lib/libfreetype.6.dylib: cannot execute binary file
logout

[Proces voltooid]

More information may be found in the apple crash report, most of which to be honest is beyond my comprehension. The apple crash report is attached below. How could I get gr working on my machine? Your help is very much appreciated.

Regards,

Hermen
ps: anaconda is installed in user/anaconda

--------------------------
Apple crash report deleted because problem==solved

**Comment by HermenB** [comment]
Hello again,
Today I finally got to installing gr again, but this time another issue arose. After trying the example in the "Getting started" section, I got the following error message:

>>> from gr import pygr
>>> pygr.plot([0,1,4],[3,2,5])
2015-09-02 13:25:38.461 python[1117:707] Could not locate GKSTerm.app.
2015-09-02 13:25:38.462 python[1117:707] Launching GKSTerm failed.

I figured it has something to do with XQuartz, and reinstalled that, but still no avail. Do you heve any further suggestions? I'm still on OSX 10.8.5, I should add…

Kind regards,

Hermen

PS: I continued on this thread because I couldn't find the option to create a new one...

**Comment by jheinen** [comment]
I'm sorry that there are (again) problems with the installation. I'll check this tomorrow on my office desktop. The next GR release will be self-contained and built without XQuartz, although this is not related to the current issue.

**Comment by jheinen** [comment]
As a temporary solution, please download the missing ``GKSTerm.app`` and unpack or move it to your Anaconda ``bin`` directory, e.g, if you installed Anaconda in your home directory:

    cd $HOME/anaconda/bin
    curl -O http://gr-framework.org/downloads/GKSTerm.zip
    open GKSTerm.zip
    rm GKSTerm.zip

 Sorry for the inconvenience ...

**Comment by HermenB** [comment]
Thank you for this solution, I'll try it today. Just for my knowledge, what is GKSTerm.app exactly? When I googled it, I only found references to the gr-website. Is it an in-house developed product?
And to verify, as far as I know the only requirement for gr is pyopengl, is that correct? Or do I need other programs / packages, too? Specifically, in the gr code I found references to .xcodeproj, do I need Xcode to be installed?

**Comment by jheinen** [comment]
``GKSTerm.app`` is part of the GR framework - it is the GR's native graphics driver for OS X. The requirements for GR are shown in the installation section of the website.

With the next release, the optional packages can automatically be downloaded and built with a shell script (``3rdparty/makeself.sh``). The result is a self-contained GR distribution, thus minimizing dependencies and improving portability.

For the Python part, ``numpy`` is the only requirement. To run all the demos, you might have to install some other packages, e.g. ``scipy`` or ``pyaudio``, but those are note required for normal usage.

 ``Xcode`` is only needed, if you want to build the GR framework from source.

**Comment by HermenB** [comment]
Thank you, this worked! I am currently trying out some of the demos and so far, so good! Sometimes it seems not to work, but after a kernel restart it does. Thank you very much for your patience with helping me out.

kind regards,

Hermen

ps: do you know where best to get pyopencl? I couldn't find it on Anaconda.
