### ISSUE TITLE
One of equation in spline.c is incorrect

### ISSUE THREAD

**Issue by shukailin** [jheinen/gr#43]
In gr/lib/gr/spline.c line 355,
The correct equation is 
R(i, 0) = 1 / (*p * C(i - 1, 0) + *q * T(i, 0) - f * R(i - 1, 1) - g *
	R(i - 2, 2));

instead of 
R(i, 0) = 1 / (*p * C(i - 1, 0) + *q * T(i, 0) - f * R(i - 1, 1) + g *
	R(i - 2, 2));

It is "-" instead of "+".

Ref: http://dl.acm.org/citation.cfm?id=214322

**Comment by jheinen** [comment]
Thanks a lot for the hint!
