### ISSUE TITLE
Resizing issue

### ISSUE THREAD

**Issue by mrtompet** [jheinen/gr#44]
_       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

Resizing issue with the following example plot

using Plots
gr()
plot(sin,(x->begin sin(2x) end),0,2π,line=4,leg=false,fill=(0,:orange))

Issue 1:
Moving the mouse towards the lower right corner of the GKSTerm window in the foreground changes the cursor shape to a two sided arrow.
Click and move the cursor to shrink the window, then release the mouse.
A black block appears within the drawing area.

Issue 2:
Select „Rotate by 90“. Resizing distorts the drawing.

**Comment by jheinen** [comment]
Fixed in https://github.com/jheinen/gr/commit/b8d10359fd2c74f5f46499198cb7821a33d0aae2. Please rebuild GR (master) to force a download of the latest GR run-time:
```julia
ENV["GRDIR"] = ""
Pkg.build("GR")
```

**Comment by mrtompet** [comment]
Thank you.
