### ISSUE TITLE
ambient lighting

### ISSUE THREAD

**Issue by nilsbecker** [jheinen/gr#54]
is it possible to create a more diffuse lighting style? in the api it seems there is only a specular light with a prescribed direction?

**Comment by FlorianRhiem** [comment]
No, ambient lighting is not part of GR3. You can set the light direction using [gr3_setlightdirection](https://github.com/jheinen/gr/blob/81b0842dba24af9d879a52c55b89a0b627157cd8/lib/gr3/gr3.h#L125).
