### ISSUE TITLE
Data URI mediatypes should be specified in svg outputs

### ISSUE THREAD

**Issue by CommunicationAnimale** [jheinen/gr#58]
Currently, when GR embeds a png image in a file saved in the svg format it uses  
```html
<image width="447" height="384" xlink:href="data:;base64, ... />
```
However, according to [the section about the syntax of data URIS on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs#Syntax), if no mediatype is specified, the default is `text/plain;charset=US-ASCII`. This behavior causes compatibility issues with programs such as gnome image viewer and ffmpeg.

The fix is to specify the mediatype like so:
```html
<image width="447" height="384" xlink:href="data:image/png;base64, ... />
```
I can't really read C code, but it seems that this line is printed by [this piece of code](https://github.com/jheinen/gr/blob/71eb5ee0f10d7e40a04a890dece3ae7f8a8716a0/lib/gks/plugin/svgplugin.cxx#L1068) in the file svgplugin.cxx.

**Comment by jheinen** [comment]
Has been fixed in the current release.
