### ISSUE TITLE
DOC: gr.herrorbars, gr.verrorbars wrong documentation for e1, e2

### ISSUE THREAD

**Issue by cfelder** [jheinen/gr#6]
The parameters e1, e2 do not define the absolute deviation at a given point (px, py).

- We assume we have a given point (px, py).
- and the absolute deviation at a give point in negative and positive direction (dneg, dpos).

Then e1, e2 defines the following:
gr.verrorbars:
e1 = py - dneg
e2 = py + dpos
gr.herrorbars:
e1 = px - dneg
e2 = px + dpos

We should fix the documentation for both.

**Comment by jheinen** [comment]
In my opinion we should not change the documentation but the error bar routines in the GR library:

gr_verrorbars:

    x = px[i];
    x1 = x_log(x_lin(x) - tick);
    x2 = x_log(x_lin(x) + tick);
    y1 = py[i] - e1[i];
    y2 = py[i] + e2[i];

gr_herrorbars:

    y = py[i];
    y1 = y_log(y_lin(y) - tick);
    y2 = y_log(y_lin(y) + tick);
    x1 = px[i] - e1[i];
    x2 = px[i] + e2[i];

The routines would then be compatible with error bar functions from other graphics libraries / applications, e.g. MATLAB.

**Comment by jheinen** [comment]
The documentation has been corrected.
