### ISSUE TITLE
axes2d mixed type arguments 

### ISSUE THREAD

**Issue by lazarusA** [jheinen/gr#68]
Within the latest #master branch of GR, the option **axes2d** works like follows: 

axes2d(x_tick::Real, y_tick::Real, x_org::Real, y_org::Real, major_x::Int, major_y::Int, tick_size::Real)

this part 
**x_org::Real, y_org::Real, major_x::Int, major_y::Int** 
is my problem right now. I'm trying to implement a zoom widget, and I need to be able to pass on Float64 values(not  ::Int ). Actually, in general, I think it will be better only to call Floats. (or is a way around this problem). 

Something similar should be implemented for **setwindow**, where only ::Real values are required.

**Comment by jheinen** [comment]
But how should those floats be interpreted? `major_x` and `major_y` are counts, e.g. 2 means, every 2nd tick mark is a major tick and labeled!?

**Comment by lazarusA** [comment]
Ohh I see. Sorry, my bad. I just realized that. Everythings fine now! This is not an issue.
