### ISSUE TITLE
Ruby bindings

### ISSUE THREAD

**Issue by v0dro** [jheinen/gr#72]
We're planning to use GR as a rendering backend for [rubyplot](https://github.com/sciruby/rubyplot).

Would be great to see Ruby bindings ship with GR.

**Comment by FlorianRhiem** [comment]
Hello Sameer,

I'm glad to hear that you're using GR for rubyplot. I don't think any the current GR developers uses Ruby, so we could not maintain the bindings ourself.

We keep full-fledged bindings/wrappers in seperate projects, e.g. [jheinen/GR.jl](https://github.com/jheinen/GR.jl) for Julia or [sciapp/python-gr](https://github.com/sciapp/python-gr/) for Python, so they can be developed and released independently of the GR runtime. You could move your bindings to a seperate project, add information on how to use it to the [GR documentation](https://github.com/sciapp/gr-documentation) and then it'd be on the same level as the other bindings.
