### ISSUE TITLE
Doxygen documentation

### ISSUE THREAD

**Issue by v0dro** [jheinen/gr#75]
Would be great and extremely useful to have the C API properly documented using the standard Doxygen format. If the contributors are OK with this I can start sending some patches as I build the Ruby bindings.

**Comment by FlorianRhiem** [comment]
We are using doxygen to generate the [API reference](http://gr-framework.org/c-gr.html) with a [Doxyfile](https://github.com/sciapp/gr-documentation/blob/master/Doxyfile) in the [gr-documentation](https://github.com/sciapp/gr-documentation) repository. The doxygen XML output is then processed by [breathe](https://breathe.readthedocs.io/en/latest/) so we can integrate it with the rest of our documentation. Examples for this can be found in [gr.c](https://github.com/sciapp/gr/blob/27310ee9af475521d60e29a601431a923135b433/lib/gr/gr.c#L2200).

Obviously there are still plenty of undocumented functions in the C API and I'd be happy to see that change. :)

**Comment by v0dro** [comment]
Great. I'll send some PRs through as I use GR.
